<header class="header" role="banner">
  <div class="header--inner">
    <a href="%TIDY[auth_home_link]" class="back-link--wrapper js-toplink"><img src="/public/arrow-left.png" class="back-link"/></a>
    <a href="%TIDY[auth_home_link]" class="logo--wrapper js-toplink"><img src="/public/logo.png" class="logo"/></a>
    <span class="aak-logo--wrapper"><img src="/public/aak-logo.png" class="aak-logo"/></span>
  </div>
</header>