<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name="viewport" content="width=device-width"/>
<link rel="stylesheet" href="/public/styles.css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700|Source+Sans+Pro:400,600,700" rel="stylesheet">
<script type="text/javascript" src="/public/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="/public/hide-password.min.js"></script>
<script type="text/javascript" src="/public/jquery.cookie.js"></script>
<script type="text/javascript" src="/public/jquery.h5validate.js"></script>
<script type="text/javascript" src="/public/html5shiv.js"></script>
<script type="text/javascript" src="/public/scripts.js"></script>