<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name="viewport" content="width=device-width"/>
<link rel="stylesheet" href="/public/styles.css"/>
<script type="text/javascript" src="/public/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="/public/hide-password.min.js"></script>
<script type="text/javascript" src="/public/jquery.cookie.js"></script>
<script type="text/javascript" src="/public/jquery.h5validate.js"></script>
<script type="text/javascript" src="/public/common.js"></script>